### ISSUE TITLE
 A circular dependency has been detected inside RootTestModule. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()".

### ISSUE THREAD

**Issue by nguyennhukhanh** [tkxksdl2/nestjs-test-gen#2]
A circular dependency has been detected inside RootTestModule. Please, make sure that each side of a bidirectional relationships are decorated with "forwardRef()". Note that circular relationships between custom providers (e.g., factories) are not supported since functions cannot be called more than once.
````
      44 |
      45 |   beforeEach(async () => {
    > 46 |     const module = await Test.createTestingModule({
         |                    ^
      47 |       imports: [],
      48 |       providers: [
      49 |         OtpService,

      at NestContainer.addProvider (../node_modules/@nestjs/core/injector/container.js:146:19)
      at DependenciesScanner.insertProvider (../node_modules/@nestjs/core/scanner.js:235:35)
      at ../node_modules/@nestjs/core/scanner.js:119:18
          at Array.forEach (<anonymous>)
      at DependenciesScanner.reflectProviders (../node_modules/@nestjs/core/scanner.js:118:19)
      at DependenciesScanner.scanModulesForDependencies (../node_modules/@nestjs/core/scanner.js:99:18)
      at DependenciesScanner.scan (../node_modules/@nestjs/core/scanner.js:31:9)
      at TestingModuleBuilder.compile (../node_modules/@nestjs/testing/testing-module.builder.js:70:9)
      at Object.<anonymous> (modules/auth/otp.service.spec.ts:46:20)```

**Comment by nguyennhukhanh** [comment]
I fixed this by removing the comma. When generating the code, there was an extra comma in the provider!
